### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by Searchcat37** [MauriceNino/dashdot#1056]
### Description of the bug

Dash. is failing to start and just errors out.

### How to reproduce

1. install Dash. with
```
 git clone https://github.com/MauriceNino/dashdot ^
  && cd dashdot ^
  && yarn ^
  && yarn build:prod
```
2. run `yarn start`
3. Errors

### Relevant log output

```shell
Version file not found. This is normal on from-source builds.
listening on *:3001
Acquiring Windows Persistent Powershell
Could not get default iface path
Using default network interface with no modifications
Using host os version from "/etc/os-release"
TypeError: Cannot read properties of undefined (reading 'type')
    at C:\Users\Searching-Ti-02\Desktop\dev dashdot\dist\apps\server\main.js:1:1689122
    at Generator.next (<anonymous>)
    at a (C:\Users\Searching-Ti-02\Desktop\dev dashdot\dist\apps\server\main.js:1:3472)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Releasing Windows Persistent Powershell
```

### Info output of dashdot cli

```shell
yarn cli info

show general information about your installation

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.handler (C:\Users\Searching-Ti-02\Desktop\dev dashdot\dist\apps\cli\main.js:19960:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Where is your instance running?

Desktop PC (Windows)

**Comment by MauriceNino** [comment]
Can you please try executing `yarn cli raw-data --storage` and post the output?

**Comment by Searchcat37** [comment]
<details>
  <summary>Output:</summary>

```js
(node:6600) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
const disks =  [
  {
    device: '\\\\.\\PHYSICALDRIVE1',
    type: 'Unspecified',
    name: 'Seagate OneTouch HDD SCSI Disk Device',
    vendor: '',
    size: 1000202273280,
    bytesPerSector: 512,
    totalCylinders: 121601,
    totalHeads: 255,
    totalSectors: 1953520065,
    totalTracks: 31008255,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: '1707',
    serialNum: '00000000NABPBNVV',
    interfaceType: 'USB',
    smartStatus: 'Ok',
    temperature: null
  },
  {
    device: '\\\\.\\PHYSICALDRIVE0',
    type: 'SSD',
    name: 'Samsung SSD 850 PRO 128GB',
    vendor: 'Samsung',
    size: 128034708480,
    bytesPerSector: 512,
    totalCylinders: 15566,
    totalHeads: 255,
    totalSectors: 250067790,
    totalTracks: 3969330,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: 'EXM02B6Q',
    serialNum: 'S24ZNSAG353327P',
    interfaceType: 'SATA',
    smartStatus: 'Ok',
    temperature: null
  }
]
const sizes =  [
  {
    fs: 'C:',
    type: 'NTFS',
    size: 127377149952,
    used: 96475131904,
    available: 30902018048,
    use: 75.74,
    mount: 'C:',
    rw: true
  },
  {
    fs: 'D:',
    type: 'exFAT',
    size: 1000170586112,
    used: 531570491392,
    available: 468600094720,
    use: 53.15,
    mount: 'D:',
    rw: true
  }
]
const blocks =  [
  {
    name: 'C:',
    identifier: 'C:',
    type: 'disk',
    fsType: 'ntfs',
    mount: 'C:',
    size: '127377149952',
    physical: 'Local',
    uuid: '00C25B4B',
    label: '',
    model: '',
    serial: '00C25B4B',
    removable: false,
    protocol: '',
    group: '',
    device: '\\\\.\\PHYSICALDRIVE0'
  },
  {
    name: 'D:',
    identifier: 'D:',
    type: 'disk',
    fsType: 'exfat',
    mount: 'D:',
    size: '1000170586112',
    physical: 'Local',
    uuid: '619869FC',
    label: 'One Touch',
    model: '',
    serial: '619869FC',
    removable: false,
    protocol: '',
    group: '',
    device: '\\\\.\\PHYSICALDRIVE1'
  }
]
```

</details>

**Comment by loznic89** [comment]
> Can you please try executing `yarn cli raw-data --storage` and post the output?


F:\dashdot>yarn start
Version file not found. This is normal on from-source builds.
listening on *:3001
Acquiring Windows Persistent Powershell
Could not get default iface path
Using default network interface with no modifications
Using os-release from
TypeError: Cannot read properties of undefined (reading 'type')
    at F:\dashdot\dist\apps\server\main.js:1:1236569
    at Generator.next (<anonymous>)
    at a (F:\dashdot\dist\apps\server\main.js:1:3511)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Releasing Windows Persistent Powershell
