### ISSUE TITLE
[Bug] Invalid or incomplete static data loaded!

### ISSUE THREAD

**Issue by bannert1337** [MauriceNino/dashdot#888]
### Description of the bug

<img width="1720" alt="thorium_fUgeOrhei6" src="https://github.com/MauriceNino/dashdot/assets/58707896/4ef8cb61-3b40-4661-9bb7-89596c491797">
When accessing dashdot the error `Invalid or incomplete static data loaded!` is displayed.

### How to reproduce

Environment variables:
```
DASHDOT_ACCEPT_OOKLA_EULA=true
DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
DASHDOT_ENABLE_CPU_TEMPS=true
DASHDOT_RUNNING_IN_DOCKER=true
NODE_VERSION=18.16.0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
YARN_VERSION=1.22.19
```

### Relevant log output

```shell
RangeError: Invalid array length
    at /app/dist/apps/api/main.js:2:915270
    at Array.flatMap (<anonymous>)
    at /app/dist/apps/api/main.js:2:915255
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/apps/api/main.js:12:23343)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
```

### Info output of dashdot cli

```shell
yarn run v1.22.19
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.16.0
Dash: 5.2.1

Cwd: /app
Hash: 4b43ad634751facea788b9c827528f74adae95f1
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.19s.
```

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Linux Server

### Additional context

After I added these environment variables to the container, the described behaviour started.
```
DASHDOT_ACCEPT_OOKLA_EULA=true
DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
DASHDOT_ENABLE_CPU_TEMPS=true
DASHDOT_RUNNING_IN_DOCKER=true
```

**Comment by bannert1337** [comment]
By testing, I identified that `DASHDOT_ENABLE_CPU_TEMPS=true` causes the bug.

**Comment by MauriceNino** [comment]
Hello there, thanks for identifying the problem. Can you please post the output of the following command:
```
docker exec CONTAINER yarn cli raw-data --cpu
```

**Comment by bannert1337** [comment]
```
<details>
  <summary>Output:</summary>

```js
const cpuInfo =  {
  manufacturer: 'Intel',
  brand: 'Gen Intel® Core™ i5-13500',
  vendor: 'Intel',
  family: '6',
  model: '191',
  stepping: '2',
  revision: '',
  voltage: '',
  speed: 2.5,
  speedMin: 0.8,
  speedMax: 4.8,
  governor: 'powersave',
  cores: 20,
  physicalCores: 14,
  performanceCores: 6,
  efficiencyCores: 8,
  processors: 1,
  socket: '',
  flags: 'fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr flush_l1d arch_capabilities',
  virtualization: true,
  cache: { l1d: 557056, l1i: 720896, l2: 11534336, l3: 25165824 }
}
const cpuLoad =  {
  avgLoad: 0.03,
  currentLoad: 3.9832615561589617,
  currentLoadUser: 2.928369133065314,
  currentLoadSystem: 0.8334068738382707,
  currentLoadNice: 0.2214855492553772,
  currentLoadIdle: 96.01673844384105,
  currentLoadIrq: 0,
  rawCurrentLoad: 188459770,
  rawCurrentLoadUser: 138549720,
  rawCurrentLoadSystem: 39430920,
  rawCurrentLoadNice: 10479130,
  rawCurrentLoadIdle: 4542833100,
  rawCurrentLoadIrq: 0,
  cpus: [
    {
      load: 7.727130397099352,
      loadUser: 5.427449484664231,
      loadSystem: 1.648041654875335,
      loadNice: 0.6516392575597859,
      loadIdle: 92.27286960290066,
      loadIrq: 0,
      rawLoad: 17641840,
      rawLoadUser: 12391430,
      rawLoadSystem: 3762650,
      rawLoadNice: 1487760,
      rawLoadIdle: 210668530,
      rawLoadIrq: 0
    },
    {
      load: 1.0532375349881788,
      loadUser: 0.8983300485026652,
      loadSystem: 0.14232402318588025,
      loadNice: 0.012583463299633427,
      loadIdle: 98.94676246501182,
      loadIrq: 0,
      rawLoad: 2542810,
      rawLoadUser: 2168820,
      rawLoadSystem: 343610,
      rawLoadNice: 30380,
      rawLoadIdle: 238885160,
      rawLoadIrq: 0
    },
    {
      load: 8.379234079881575,
      loadUser: 5.828905397626031,
      loadSystem: 1.7758162230324295,
      loadNice: 0.7745124592231147,
      loadIdle: 91.62076592011842,
      loadIrq: 0,
      rawLoad: 19104130,
      rawLoadUser: 13289540,
      rawLoadSystem: 4048750,
      rawLoadNice: 1765840,
      rawLoadIdle: 208889620,
      rawLoadIrq: 0
    },
    {
      load: 0.9511362390649791,
      loadUser: 0.8297069313196282,
      loadSystem: 0.10966420118092206,
      loadNice: 0.011765106564428732,
      loadIdle: 99.04886376093502,
      loadIrq: 0,
      rawLoad: 2298390,
      rawLoadUser: 2004960,
      rawLoadSystem: 265000,
      rawLoadNice: 28430,
      rawLoadIdle: 239348380,
      rawLoadIrq: 0
    },
    {
      load: 8.768996086791859,
      loadUser: 6.145048938141294,
      loadSystem: 1.8021032232073388,
      loadNice: 0.8218439254432256,
      loadIdle: 91.23100391320814,
      loadIrq: 0,
      rawLoad: 19981850,
      rawLoadUser: 14002680,
      rawLoadSystem: 4106440,
      rawLoadNice: 1872730,
      rawLoadIdle: 207887450,
      rawLoadIrq: 0
    },
    {
      load: 0.94354732573645,
      loadUser: 0.8219169011204949,
      loadSystem: 0.1091193227202107,
      loadNice: 0.012511101895744406,
      loadIdle: 99.05645267426355,
      loadIrq: 0,
      rawLoad: 2279850,
      rawLoadUser: 1985960,
      rawLoadSystem: 263660,
      rawLoadNice: 30230,
      rawLoadIdle: 239345550,
      rawLoadIrq: 0
    },
    {
      load: 9.164884687251194,
      loadUser: 6.3898719153251164,
      loadSystem: 1.8863801023581157,
      loadNice: 0.8886326695679612,
      loadIdle: 90.8351153127488,
      loadIrq: 0,
      rawLoad: 20867240,
      rawLoadUser: 14548900,
      rawLoadSystem: 4295040,
      rawLoadNice: 2023300,
      rawLoadIdle: 206819640,
      rawLoadIrq: 0
    },
    {
      load: 0.9301306884523245,
      loadUser: 0.8089993144662845,
      loadSystem: 0.10897188318479,
      loadNice: 0.01215949080125002,
      loadIdle: 99.06986931154768,
      loadIrq: 0,
      rawLoad: 2247400,
      rawLoadUser: 1954720,
      rawLoadSystem: 263300,
      rawLoadNice: 29380,
      rawLoadIdle: 239374560,
      rawLoadIrq: 0
    },
    {
      load: 9.204256558898287,
      loadUser: 6.363379895917723,
      loadSystem: 1.8824343110622226,
      loadNice: 0.9584423519183412,
      loadIdle: 90.79574344110172,
      loadIrq: 0,
      rawLoad: 20949130,
      rawLoadUser: 14483220,
      rawLoadSystem: 4284470,
      rawLoadNice: 2181440,
      rawLoadIdle: 206653500,
      rawLoadIrq: 0
    },
    {
      load: 0.9487956153051803,
      loadUser: 0.8077766679179328,
      loadSystem: 0.13086750416625248,
      loadNice: 0.010151443220994974,
      loadIdle: 99.05120438469483,
      loadIrq: 0,
      rawLoad: 2291740,
      rawLoadUser: 1951120,
      rawLoadSystem: 316100,
      rawLoadNice: 24520,
      rawLoadIdle: 239250270,
      rawLoadIrq: 0
    },
    {
      load: 8.636415174757305,
      loadUser: 6.319822078903109,
      loadSystem: 2.0091985568545643,
      loadNice: 0.3073945389996306,
      loadIdle: 91.3635848252427,
      loadIrq: 0,
      rawLoad: 20070610,
      rawLoadUser: 14686960,
      rawLoadSystem: 4669280,
      rawLoadNice: 714370,
      rawLoadIdle: 212324540,
      rawLoadIrq: 0
    },
    {
      load: 1.4740298864034564,
      loadUser: 0.8727208723244353,
      loadSystem: 0.5980733249659396,
      loadNice: 0.0032356891130815657,
      loadIdle: 98.52597011359654,
      loadIrq: 0,
      rawLoad: 3398430,
      rawLoadUser: 2012090,
      rawLoadSystem: 1378880,
      rawLoadNice: 7460,
      rawLoadIdle: 227155240,
      rawLoadIrq: 0
    },
    {
      load: 5.193606412621672,
      loadUser: 3.7675616501386533,
      loadSystem: 1.3986966389198214,
      loadNice: 0.02734812356319796,
      loadIdle: 94.80639358737832,
      loadIrq: 0,
      rawLoad: 12343970,
      rawLoadUser: 8954600,
      rawLoadSystem: 3324370,
      rawLoadNice: 65000,
      rawLoadIdle: 225332300,
      rawLoadIrq: 0
    },
    {
      load: 4.160038329245405,
      loadUser: 3.1398729468897506,
      loadSystem: 1.0013205607133941,
      loadNice: 0.01884482164226049,
      loadIdle: 95.83996167075459,
      loadIrq: 0,
      rawLoad: 9938270,
      rawLoadUser: 7501110,
      rawLoadSystem: 2392140,
      rawLoadNice: 45020,
      rawLoadIdle: 228960250,
      rawLoadIrq: 0
    },
    {
      load: 3.3182287015519876,
      loadUser: 2.573173873781478,
      loadSystem: 0.7301794962232167,
      loadNice: 0.014875331547292966,
      loadIdle: 96.68177129844801,
      loadIrq: 0,
      rawLoad: 7959110,
      rawLoadUser: 6172020,
      rawLoadSystem: 1751410,
      rawLoadNice: 35680,
      rawLoadIdle: 231901090,
      rawLoadIrq: 0
    },
    {
      load: 2.688985683112371,
      loadUser: 2.1550814852655513,
      loadSystem: 0.5207128013330341,
      loadNice: 0.013191396513785552,
      loadIdle: 97.31101431688764,
      loadIrq: 0,
      rawLoad: 6463890,
      rawLoadUser: 5180470,
      rawLoadSystem: 1251710,
      rawLoadNice: 31710,
      rawLoadIdle: 233920060,
      rawLoadIrq: 0
    },
    {
      load: 2.2494324969188417,
      loadUser: 1.847120543952181,
      loadSystem: 0.39023989415803745,
      loadNice: 0.01207205880862322,
      loadIdle: 97.75056750308116,
      loadIrq: 0,
      rawLoad: 5414860,
      rawLoadUser: 4446410,
      rawLoadSystem: 939390,
      rawLoadNice: 29060,
      rawLoadIdle: 235306300,
      rawLoadIrq: 0
    },
    {
      load: 1.93212803250148,
      loadUser: 1.6250905900909691,
      loadSystem: 0.29559361000962725,
      loadNice: 0.011443832400883673,
      loadIdle: 98.06787196749852,
      loadIrq: 0,
      rawLoad: 4656490,
      rawLoadUser: 3916520,
      rawLoadSystem: 712390,
      rawLoadNice: 27580,
      rawLoadIdle: 236346690,
      rawLoadIrq: 0
    },
    {
      load: 1.7263598000897766,
      loadUser: 1.4787981205115297,
      loadSystem: 0.23690971905775468,
      loadNice: 0.010651960520492358,
      loadIdle: 98.27364019991023,
      loadIrq: 0,
      rawLoad: 4163570,
      rawLoadUser: 3566510,
      rawLoadSystem: 571370,
      rawLoadNice: 25690,
      rawLoadIdle: 237012690,
      rawLoadIrq: 0
    },
    {
      load: 1.593962008801833,
      loadUser: 1.380735570911705,
      loadSystem: 0.2034667002517681,
      loadNice: 0.009759737638359823,
      loadIdle: 98.40603799119818,
      loadIrq: 0,
      rawLoad: 3846190,
      rawLoadUser: 3331680,
      rawLoadSystem: 490960,
      rawLoadNice: 23550,
      rawLoadIdle: 237451280,
      rawLoadIrq: 0
    }
  ]
}
const cpuTemp =  {
  main: 36,
  cores: [
    36, 36, 30, 31, 30, 31,
    32, 31, 33, 30, 32, 30,
    36, 36
  ],
  max: 36,
  socket: [ 27.8 ],
  chipset: null
}
```

</details>
```

**Comment by MauriceNino** [comment]
Hi, the problem should be fixed in the latest release. Can you please let me know if that is the case and comment, so I can reopen the issue if not?
