### ISSUE TITLE
[Bug] DASHDOT_STORAGE_ITEMS_PER_PAGE does not work

### ISSUE THREAD

**Issue by ayykamp** [MauriceNino/dashdot#926]
### Description of the bug

DASHDOT_STORAGE_ITEMS_PER_PAGE currently does not work.

Here is what it looks like with 6 drives and DASHDOT_STORAGE_ITEMS_PER_PAGE set to 6:
![image](https://github.com/MauriceNino/dashdot/assets/32194363/d70e029a-9912-44a9-93d0-5441cf314a11)

### How to reproduce

Have more than 3 drives and set DASHDOT_STORAGE_ITEMS_PER_PAGE to a value above 3. Setting it to a lower value also does nothing.

### Relevant log output

```shell
Na
```

### Info output of dashdot cli

```shell
yarn run v1.22.19
$ node dist/apps/cli/main.js info
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'systeminformation'
Require stack:
- /app/dist/apps/cli/apps/cli/src/main.js
- /app/dist/apps/cli/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._resolveFilename (/app/dist/apps/cli/main.js:32:36)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/app/dist/apps/cli/apps/cli/src/main.js:26:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/dist/apps/cli/apps/cli/src/main.js',
    '/app/dist/apps/cli/main.js'
  ]
}

Node.js v18.17.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What browsers are you seeing the problem on?

Firefox, Chrome

### Where is your instance running?

Linux Server

**Comment by MauriceNino** [comment]
Hi there. That's weird, I will look into this when I get some time.

**Comment by MauriceNino** [comment]
This was actually a typo in the documentation - the actual environment variable is `DASHDOT_STORAGE_WIDGET_ITEMS_PER_PAGE`. The docs will be updated on the next release.
