### ISSUE TITLE
[Bug] Network interface speed not shown 

### ISSUE THREAD

**Issue by tcfjr** [MauriceNino/dashdot#934]
### Description of the bug

On a Synology DS220+ running DSM 7.1.1.42962 with the latest Dashdot in a docker container, the speed of the network interface is not shown.  The log file shows an error reading /sys/class/net/ovs_eth0/speed - see the log entry below for details.  

I logged into the system as UID 0 using SSH, and get a similar error trying to read the speed file:

```
root@DS220A1:/sys/class/net/ovs_eth0# cat speed
cat: speed: Invalid argument
```
Other files in the same directory with similar permissions can be read, but the duplex file also gives the Invalid argument error:

```
root@DS220A1:/sys/class/net/ovs_eth0# cat address
90:09:d0:17:fc:33
root@DS220A1:/sys/class/net/ovs_eth0# cat type
1
root@DS220A1:/sys/class/net/ovs_eth0# cat duplex
cat: duplex: Invalid argument
```

### How to reproduce

Run Dash. on a Synology DSM using this docker compose:

```
version: "3.9"
services:
  dashdot:
    container_name: Dashdot
    image: mauricenino/dashdot
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    volumes:
      - /:/mnt/host:ro
    ports:
      - 7512:3001
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_OVERRIDE_OS: Synology DSM
      DASHDOT_ACCEPT_OOKLA_EULA: true
      DASHDOT_STORAGE_ITEMS_PER_PAGE: 1
```

The speed of the network adaptor(s) is not shown.

![chrome_NQyZLBeV7y](https://github.com/MauriceNino/dashdot/assets/17212897/5b04b3f1-5d21-49e1-ac03-d98ba812d690)

### Relevant log output

```shell
yarn run v1.22.19
$ node .
listening on *:3001
Using default network interface "ovs_eth0"
Using host os version from "/etc/os-release"
Error: Command failed: cat /mnt/host/sys/class/net/ovs_eth0/speed
cat: read error: Invalid argument
    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:323:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'cat /mnt/host/sys/class/net/ovs_eth0/speed',
  stdout: '',
  stderr: 'cat: read error: Invalid argument\n'
}
Static Server Info: {
  os: {
    arch: 'x64',
    distro: 'Alpine Linux',
    kernel: '4.4.180+',
    platform: 'linux',
    release: '3.18.3',
    uptime: 740716.65,
    dash_version: '5.2.3',
    dash_buildhash: '80366ce356f35250aec5b2aa1c46e838fb492b66'
  },
  cpu: {
    brand: 'Intel',
    model: 'Celeron® J4025',
    cores: 2,
    ecores: 0,
    pcores: 2,
    threads: 2,
    frequency: 2
  },
  ram: {
    size: 6056890368,
    layout: [
      { brand: 'Samsung', type: 'DDR4', frequency: 2400 },
      { brand: 'Synology', type: 'DDR4', frequency: 2400 }
    ]
  },

  storage: [
    {
      raidLabel: '',
      raidName: 'md0',
      raidType: 1,
      size: 7995257520128,
      disks: [
        { device: 'sata1', brand: 'Seagate', type: 'HD' },
        { device: 'sata2', brand: 'Seagate', type: 'HD' }
      ]
    },
    {
      size: 125829120,
      disks: [ { device: 'synoboot', brand: 'Synology', type: 'HD' } ]
    },
    {
      size: 1817182208,
      disks: [ { device: 'zram0', brand: 'zram0', type: 'SSD' } ]
    },
    {
      size: 1817182208,
      disks: [ { device: 'zram1', brand: 'zram1', type: 'SSD' } ]
    }
  ],

  network: {
    interfaceSpeed: 0,
    speedDown: 0,
    speedUp: 0,
    type: 'Wired',
    publicIp: ''
  },
  gpu: { layout: [] },
  config: {
    port: 3001,
    running_in_docker: true,
    accept_ookla_eula: true,
    use_network_interface: undefined,
    speed_test_from_path: undefined,
    fs_device_filter: [],
    fs_type_filter: [
      'cifs',
      '9p',
      'fuse.rclone',
      'fuse.mergerfs',
      'nfs4',
      'iso9660',
      'fuse.shfs'
    ],
    fs_virtual_mounts: [],
    disable_integrations: false,
    show_dash_version: undefined,
    show_host: false,
    custom_host: undefined,
    page_title: 'dash.',
    use_imperial: false,
    always_show_percentages: false,
    widget_list: [ 'os', 'cpu', 'storage', 'ram', 'network' ],
    os_label_list: [ 'os', 'arch', 'up_since' ],
    cpu_label_list: [ 'brand', 'model', 'cores', 'threads', 'frequency' ],
    storage_label_list: [ 'brand', 'type', 'size', 'raid' ],
    ram_label_list: [ 'brand', 'type', 'size', 'frequency' ],
    network_label_list: [ 'type', 'speed_up', 'speed_down', 'interface_speed' ],
    gpu_label_list: [ 'brand', 'model', 'memory' ],
    os_widget_grow: 2.5,
    os_widget_min_width: 300,
    enable_cpu_temps: true,
    cpu_widget_grow: 4,
    cpu_widget_min_width: 500,
    cpu_shown_datapoints: 20,
    cpu_poll_interval: 1000,
    storage_widget_items_per_page: 3,
    storage_widget_grow: 3.5,
    storage_widget_min_width: 500,
    storage_poll_interval: 60000,
    ram_widget_grow: 4,
    ram_widget_min_width: 500,
    ram_shown_datapoints: 20,
    ram_poll_interval: 1000,
    speed_test_interval: 240,
    network_widget_grow: 6,
    network_widget_min_width: 500,
    network_shown_datapoints: 20,
    network_poll_interval: 1000,
    gpu_widget_grow: 6,
    gpu_widget_min_width: 700,
    gpu_shown_datapoints: 20,
    gpu_poll_interval: 1000,
    override: {
      os: 'Synology DSM',
      arch: undefined,
      cpu_brand: undefined,
      cpu_model: undefined,
      cpu_cores: undefined,
      cpu_threads: undefined,
      cpu_frequency: undefined,
      ram_brand: undefined,
      ram_size: undefined,
      ram_type: undefined,
      ram_frequency: undefined,
      network_type: undefined,
      network_speed_up: undefined,
      network_speed_down: undefined,
      network_interface_speed: undefined,
      network_public_ip: undefined,
      storage_brands: {},
      storage_sizes: {},
      storage_types: {},
      gpu_brands: [],
      gpu_models: [],
      gpu_memories: []
    }
  }
}
Running speed-test (this may take a few minutes)...
First measurement [Network]: { up: 0, down: 0 }
First measurement [CPU]: [
  { load: 9.488349552818, temp: 40, core: 0 },
  { load: 9.850310116681873, temp: 41, core: 1 }
]
First measurement [RAM]: 3387809792
First measurement [Storage]: [ 1828978688, 0, 0, 0 ]
Speed-test completed successfully [ookla] { speedDown: 377906904, speedUp: 10721576, publicIp: undefined }
```

### Info output of dashdot cli

```shell
$ sudo docker exec Dashdot yarn cli info
Password: 
yarn run v1.22.19
$ node dist/apps/cli/main.js info
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'systeminformation'
Require stack:
- /app/dist/apps/cli/apps/cli/src/main.js
- /app/dist/apps/cli/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._resolveFilename (/app/dist/apps/cli/main.js:32:36)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/app/dist/apps/cli/apps/cli/src/main.js:26:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/dist/apps/cli/apps/cli/src/main.js',
    '/app/dist/apps/cli/main.js'
  ]
}

Node.js v18.17.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Other (Please specify below)

### Additional context

Synology DS220+ DSM 7.1.1

**Comment by MauriceNino** [comment]
Hi in this case I would suggest using the environment variable [`DASHDOT_OVERRIDE_NETWORK_INTERFACE_SPEED`](https://getdashdot.com/docs/config/overrides#dashdot_override_network_interface_speed) to set the interface speed manually.

Sometimes it can happen that some information can not be correctly gathered.

Unless this is a recurring issue for a lot of users, I will close this for now.
