### ISSUE TITLE
[Bug] Storage is Reported as 0% Usage

### ISSUE THREAD

**Issue by jordan-wirth** [MauriceNino/dashdot#944]
### Description of the bug

This appears to happen for me on multiple installations.

![image](https://github.com/MauriceNino/dashdot/assets/20449792/65e2fe04-a06b-44dd-ad89-9a1361b527c8)

### What browsers are you seeing the problem on?

Firefox

### Where is your instance running?

Linux Server

**Comment by vorwd** [comment]
adding that I am also having this issue.

docker exec dashdot yarn cli raw-data --storage
yarn run v1.22.19
$ node dist/apps/cli/main.js raw-data --storage
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'systeminformation'
Require stack:
- /app/dist/apps/cli/apps/cli/src/main.js
- /app/dist/apps/cli/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._resolveFilename (/app/dist/apps/cli/main.js:32:36)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/app/dist/apps/cli/apps/cli/src/main.js:26:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/dist/apps/cli/apps/cli/src/main.js',
    '/app/dist/apps/cli/main.js'
  ]
}

Node.js v18.17.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MauriceNino** [comment]
@blackadar @vorwd Sorry for the inconvenience. The command should now be working on the latest release. If you could retry it and paste the output, I can look into your problems.

**Comment by blackadar** [comment]
On the latest release, it appears the bars are all completely full (when the disks are most definitely not full):
![image](https://github.com/MauriceNino/dashdot/assets/20449792/42f6e922-67e3-4676-9f11-76256c38a53b)


And here's the output of the command which works now:
<details>
  <summary>Output:</summary>

```js
const disks =  [
  {
    device: '/dev/sda',
    type: 'HD',
    name: 'WDC WD1002FAEX-0',
    vendor: 'Western Digital',
    size: 1000204886016,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '1D05',
    serialNum: '',
    interfaceType: 'SATA',
    smartStatus: 'unknown',
    temperature: null
  },
  {
    device: '/dev/sdb',
    type: 'HD',
    name: 'ST14000VN0008-2K',
    vendor: 'Seagate',
    size: 14000519643136,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: 'SC61',
    serialNum: '',
    interfaceType: 'SATA',
    smartStatus: 'unknown',
    temperature: null
  },
  {
    device: '/dev/sdc',
    type: 'SSD',
    name: 'CT1000MX500SSD1 ',
    vendor: 'ATA',
    size: 1000204886016,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '033',
    serialNum: '',
    interfaceType: 'SATA',
    smartStatus: 'unknown',
    temperature: null
  },
  {
    device: '/dev/sdd',
    type: 'HD',
    name: 'ST14000VN0008-2K',
    vendor: 'Seagate',
    size: 14000519643136,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: 'SC61',
    serialNum: '',
    interfaceType: 'SATA',
    smartStatus: 'unknown',
    temperature: null
  },
  {
    device: '/dev/sde',
    type: 'HD',
    name: 'Elements 25A3   ',
    vendor: 'WD',
    size: 18000174383104,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '1031',
    serialNum: '',
    interfaceType: 'USB',
    smartStatus: 'unknown',
    temperature: null
  }
]
const sizes =  []
const blocks =  [
  {
    name: 'sda',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 1000204886016,
    physical: 'HDD',
    uuid: '',
    label: '',
    model: 'WDC WD1002FAEX-0',
    serial: '',
    removable: false,
    protocol: 'sata',
    group: '',
    device: '/dev/sda'
  },
  {
    name: 'sdb',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 14000519643136,
    physical: 'HDD',
    uuid: '',
    label: '',
    model: 'ST14000VN0008-2K',
    serial: '',
    removable: false,
    protocol: 'sata',
    group: '',
    device: '/dev/sdb'
  },
  {
    name: 'sdc',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 1000204886016,
    physical: 'SSD',
    uuid: '',
    label: '',
    model: 'CT1000MX500SSD1',
    serial: '',
    removable: false,
    protocol: 'sata',
    group: '',
    device: '/dev/sdc'
  },
  {
    name: 'sdd',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 14000519643136,
    physical: 'HDD',
    uuid: '',
    label: '',
    model: 'ST14000VN0008-2K',
    serial: '',
    removable: false,
    protocol: 'sata',
    group: '',
    device: '/dev/sdd'
  },
  {
    name: 'sde',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 18000174383104,
    physical: 'HDD',
    uuid: '',
    label: '',
    model: 'Elements 25A3',
    serial: '',
    removable: false,
    protocol: 'usb',
    group: '',
    device: '/dev/sde'
  },
  {
    name: 'loop0',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/bare/5',
    size: 4096,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop1',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/core22/864',
    size: 77492224,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop10',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/snapd/20671',
    size: 42393600,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop11',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/snapd-desktop-integration/83',
    size: 462848,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop12',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/core18/2812',
    size: 58363904,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop13',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/vlc/3721',
    size: 336678912,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop14',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/firefox/3626',
    size: 257945600,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop2',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/core22/1033',
    size: 77713408,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop4',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/firefox/3600',
    size: 257859584,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop5',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/firmware-updater/109',
    size: 11747328,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop6',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/gnome-42-2204/141',
    size: 521121792,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop7',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/gtk-common-themes/1535',
    size: 96141312,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop8',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/snap-store/1046',
    size: 11026432,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'loop9',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/snapd/20290',
    size: 42840064,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: ''
  },
  {
    name: 'sda1',
    type: 'part',
    fsType: '',
    mount: '',
    size: 16759808,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sda'
  },
  {
    name: 'sda2',
    type: 'part',
    fsType: 'ntfs',
    mount: '/mnt/host/media/ben/HDD',
    size: 1000186314752,
    physical: '',
    uuid: '7440B22D40B1F5C8',
    label: 'HDD',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sda'
  },
  {
    name: 'sdb1',
    type: 'part',
    fsType: '',
    mount: '',
    size: 16759808,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdb'
  },
  {
    name: 'sdb2',
    type: 'part',
    fsType: 'ntfs',
    mount: '/mnt/host/media/ben/Plex Movies',
    size: 14000500768768,
    physical: '',
    uuid: 'CE8AD89A8AD8807F',
    label: 'Plex Movies',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdb'
  },
  {
    name: 'sdc1',
    type: 'part',
    fsType: 'vfat',
    mount: '/mnt/host/boot/efi',
    size: 104857600,
    physical: '',
    uuid: '76A8-8728',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdc'
  },
  {
    name: 'sdc2',
    type: 'part',
    fsType: '',
    mount: '',
    size: 16777216,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdc'
  },
  {
    name: 'sdc3',
    type: 'part',
    fsType: 'ntfs',
    mount: '',
    size: 492568576000,
    physical: '',
    uuid: '5CACAA14ACA9E92A',
    label: 'SSD',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdc'
  },
  {
    name: 'sdc4',
    type: 'part',
    fsType: 'ntfs',
    mount: '',
    size: 532676608,
    physical: '',
    uuid: '46B0D3E3B0D3D80F',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdc'
  },
  {
    name: 'sdc5',
    type: 'part',
    fsType: 'ext4',
    mount: '/mnt/host',
    size: 506979155968,
    physical: '',
    uuid: '3a5b79e3-f286-4cb9-bf0d-49688303d6e1',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdc'
  },
  {
    name: 'sdd1',
    type: 'part',
    fsType: '',
    mount: '',
    size: 16759808,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdd'
  },
  {
    name: 'sdd2',
    type: 'part',
    fsType: 'ntfs',
    mount: '/mnt/host/media/ben/Plex TV Shows',
    size: 14000500768768,
    physical: '',
    uuid: '5896167F96165DB6',
    label: 'Plex TV Shows',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sdd'
  },
  {
    name: 'sde1',
    type: 'part',
    fsType: 'ext4',
    mount: '/mnt/host/media/ben/External A',
    size: 18000172285952,
    physical: '',
    uuid: '11e3bc5f-0955-4f58-b2ec-4568de52b773',
    label: 'External A',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: '',
    device: '/dev/sde'
  }
]
```

</details>

Thanks so much for taking the time to look into this!

**Comment by MauriceNino** [comment]
@blackadar Unfortunately it seems like your storage array is completely empty. Have you mounted the host drive into the container?

Can you maybe share your configuration?

**Comment by blackadar** [comment]
Sure! Here's the actual drive usage:
![image](https://github.com/MauriceNino/dashdot/assets/20449792/c1def740-6cbe-43fd-a791-56e77aeb2589)

And here's the docker compose:
```
  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_CUSTOM_HOST=neon
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_PAGE_TITLE=dash.neon
    ports:
      - '90:3001'
    volumes:
      - /:/mnt/host:ro
```

**Comment by MauriceNino** [comment]
Ok seems correct. Can you share more information about your config? 

- What is your drive setup?
- Are you running in a VM?
- What is your host?

Also please execute `df` on your host and also inside the container and post the output.

**Comment by blackadar** [comment]
- 2 of the drives are internal SATA drives, NTFS mounted at boot. One drive is a USB drive, ext4 also mounted automatically at boot. All mount points are under `/media/user`.
- No, just docker containers on the host
- The host is Ubuntu 23.10, almost entirely stock aside from Docker

`df` on host:
```
Filesystem       1K-blocks        Used   Available Use% Mounted on
tmpfs              3277560       72132     3205428   3% /run
/dev/sdc5        486202568   193184608   268246736  42% /
tmpfs             16387784           0    16387784   0% /dev/shm
tmpfs                 5120          12        5108   1% /run/lock
efivarfs               128          29          95  24% /sys/firmware/efi/efivars
/dev/sdc1            98304       31843       66461  33% /boot/efi
/dev/sda2        976744444    15631996   961112448   2% /media/ben/HDD
/dev/sdd2      13672364028 11808814688  1863549340  87% /media/ben/Plex TV Shows
/dev/sdb2      13672364028 10276861272  3395502756  76% /media/ben/Plex Movies
tmpfs              3277556         108     3277448   1% /run/user/1000
/dev/sde1      17507296732   201075476 16427290212   2% /media/ben/External A
```

`df` on container:
```
df: /mnt/host/media/ben/Plex\040TV\040Shows: No such file or directory
df: /mnt/host/media/ben/Plex\040Movies: No such file or directory
df: /mnt/host/media/ben/External\040A: No such file or directory
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay              486202568 193184920 268246424  42% /
tmpfs                    65536         0     65536   0% /dev
shm                      65536         0     65536   0% /dev/shm
/dev/sdc5            486202568 193184920 268246424  42% /mnt/host
udev                  16356180         0  16356180   0% /mnt/host/dev
tmpfs                 16387784         0  16387784   0% /mnt/host/dev/shm
tmpfs                  3277560     72156   3205404   2% /mnt/host/run
tmpfs                     5120        12      5108   0% /mnt/host/run/lock
tmpfs                  3277556       108   3277448   0% /mnt/host/run/user/1000
tmpfs                  3277560     72156   3205404   2% /mnt/host/run/snapd/ns
efivarfs                   128        28        95  23% /mnt/host/sys/firmware/efi/efivars
/dev/sdc1                98304     31843     66461  32% /mnt/host/boot/efi
/dev/loop0                 128       128         0 100% /mnt/host/snap/bare/5
/dev/loop1               57088     57088         0 100% /mnt/host/snap/core18/2812
/dev/loop2               75904     75904         0 100% /mnt/host/snap/core22/1033
/dev/loop3               75776     75776         0 100% /mnt/host/snap/core22/864
/dev/loop4              251904    251904         0 100% /mnt/host/snap/firefox/3600
/dev/loop5              251904    251904         0 100% /mnt/host/snap/firefox/3626
/dev/loop6               11520     11520         0 100% /mnt/host/snap/firmware-updater/109
/dev/loop7              508928    508928         0 100% /mnt/host/snap/gnome-42-2204/141
/dev/loop8               93952     93952         0 100% /mnt/host/snap/gtk-common-themes/1535
/dev/loop9               10880     10880         0 100% /mnt/host/snap/snap-store/1046
/dev/loop10              41856     41856         0 100% /mnt/host/snap/snapd/20290
/dev/loop11              41472     41472         0 100% /mnt/host/snap/snapd/20671
/dev/loop12                512       512         0 100% /mnt/host/snap/snapd-desktop-integration/83
/dev/sdc5            486202568 193184920 268246424  42% /mnt/host/var/snap/firefox/common/host-hunspell
/dev/loop13             328832    328832         0 100% /mnt/host/snap/vlc/3721
/dev/sda2            976744444  15631996 961112448   2% /mnt/host/media/ben/HDD
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/046b39ab92c9055488da835b0a0038b4b77ef112d498cbdbb842279da0994080/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/e4d20bdf2ef8e10541784926dc41564f43ce8e1ed354f6233456b60d4b0ab718/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/5e6d65ad5cf71502bce56bdb33cd18d2db0be642faede51605f5c2954f992abf/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/bd13867a162fe5f3249ee466054a3d614b63dfd659619b5db7643e571b4ab6cc/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/e5af5ce88be939123599e9f620116a8fc06ef2067d86fc9ba49a7b343d278801/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/3cc27256ee69b5cde7fad4ae5c2b18c2cebb56d57c0f4144f10276dfcf400c2c/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/6d060ba456e01dd8065a052d8b9eb18cf05b1b4720bd53349caa866cce93a522/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/88f76af4e9925e612e9cdf631af6f1e2ed1def74f0e4a16eb5e7757ff5fe76e6/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/11c0a5d827a21dfa523986dc2dc6ea4d91360e9f9a31571ece1e8bdabc6f6efd/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/e2ea2e222aa59f0c183185368882025d4bbd5b7f122d996041a5cba1f9cce6e6/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/6db9ba5a73f2d7e8c262329669e05a2ec3e37ac7f8bf31627986ecc6547db2f9/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/91d6a1b66a77bbb5bd4fc143793ccc4491b8f768705b57ae870feef7fb53b7c3/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/5d9972b897b8c8c2d6b8821c160986e31f51c4c02ebbb09c8f4b0802169264ad/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/2c94c3939798c0dc997f68ad9e9686d5c6dfa69fc52bc4e6076fdc72a79db017/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/2ddc9a10e3f5bb72e09b519c6daf37aaf40a5887fe0d114a9979b8454bff06db/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/cbe9eb188e12cd2335d65f3b59958030e7497f76cfaa1d6a02378c03072f3295/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/cd8403251575898ab5d01f844ab04b347b5f3ca76a2795f22c1e2ad024d7c717/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/cd8403251575898ab5d01f844ab04b347b5f3ca76a2795f22c1e2ad024d7c717/merged
tmpfs                    65536         0     65536   0% /mnt/host/var/lib/docker/overlay2/cd8403251575898ab5d01f844ab04b347b5f3ca76a2795f22c1e2ad024d7c717/merged/dev
shm                      65536         0     65536   0% /mnt/host/var/lib/docker/overlay2/cd8403251575898ab5d01f844ab04b347b5f3ca76a2795f22c1e2ad024d7c717/merged/dev/shm
/dev/sdc5            486202568 193184916 268246428  42% /etc/resolv.conf
/dev/sdc5            486202568 193184916 268246428  42% /etc/hostname
/dev/sdc5            486202568 193184916 268246428  42% /etc/hosts
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/d8e29ad1118691e6ad31aac7e51ed1490d7c1267e61f3dbcf01e040ff640abc9/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/030b03ed223c60ca034811ca543d5f581ec1c18f6f275495e4a4feea9bf980f5/merged
overlay              486202568 193184916 268246428  42% /mnt/host/var/lib/docker/overlay2/c57f8edaa75b4bfa04412e03511aaddfd18a92aa73eea518564dc7df92d7c7cb/merged
```

Wonder if this is an issue with Docker interacting with those mount points? Looks like `df` in the container isn't happy. Thanks for the help :)

**Comment by MauriceNino** [comment]
Hm, weird, I don't get why you have those errors. Maybe because the mount is owned by another user?

Can you please execute the following command inside the docker container and paste the output?

```
df -kPT
```

**Comment by blackadar** [comment]
Here is the container output of `df -kPT`:

```
Filesystem           Type       1024-blocks    Used Available Capacity Mounted on
overlay              overlay    486202568 195889092 265542252  42% /
tmpfs                tmpfs          65536         0     65536   0% /dev
shm                  tmpfs          65536         0     65536   0% /dev/shm
/dev/sdc5            ext4       486202568 195889092 265542252  42% /mnt/host
udev                 devtmpfs    16356180         0  16356180   0% /mnt/host/dev
tmpfs                tmpfs       16387784         0  16387784   0% /mnt/host/dev/shm
tmpfs                tmpfs        3277560    155632   3121928   5% /mnt/host/run
tmpfs                tmpfs           5120        12      5108   0% /mnt/host/run/lock
tmpfs                tmpfs        3277556       100   3277456   0% /mnt/host/run/user/1000
tmpfs                tmpfs        3277560    155632   3121928   5% /mnt/host/run/snapd/ns
efivarfs             efivarfs         128        28        95  23% /mnt/host/sys/firmware/efi/efivars
/dev/sdc1            vfat           98304     31843     66461  32% /mnt/host/boot/efi
/dev/loop0           squashfs         128       128         0 100% /mnt/host/snap/bare/5
/dev/loop1           squashfs       57088     57088         0 100% /mnt/host/snap/core18/2812
/dev/loop2           squashfs       75904     75904         0 100% /mnt/host/snap/core22/1033
/dev/loop3           squashfs       75776     75776         0 100% /mnt/host/snap/core22/864
/dev/loop5           squashfs      251904    251904         0 100% /mnt/host/snap/firefox/3626
/dev/loop6           squashfs       11520     11520         0 100% /mnt/host/snap/firmware-updater/109
/dev/loop7           squashfs      508928    508928         0 100% /mnt/host/snap/gnome-42-2204/141
/dev/loop8           squashfs       93952     93952         0 100% /mnt/host/snap/gtk-common-themes/1535
/dev/loop9           squashfs       10880     10880         0 100% /mnt/host/snap/snap-store/1046
/dev/loop10          squashfs       41856     41856         0 100% /mnt/host/snap/snapd/20290
/dev/loop11          squashfs       41472     41472         0 100% /mnt/host/snap/snapd/20671
/dev/loop12          squashfs         512       512         0 100% /mnt/host/snap/snapd-desktop-integration/83
/dev/sdc5            ext4       486202568 195889088 265542256  42% /mnt/host/var/snap/firefox/common/host-hunspell
/dev/loop13          squashfs      328832    328832         0 100% /mnt/host/snap/vlc/3721
/dev/sda2            fuseblk    976744444  15631996 961112448   2% /mnt/host/media/ben/HDD
df: /mnt/host/media/ben/Plex\040TV\040Shows: No such file or directory
df: /mnt/host/media/ben/Plex\040Movies: No such file or directory
df: /mnt/host/media/ben/External\040A: No such file or directory
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/046b39ab92c9055488da835b0a0038b4b77ef112d498cbdbb842279da0994080/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/5e6d65ad5cf71502bce56bdb33cd18d2db0be642faede51605f5c2954f992abf/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/e2ea2e222aa59f0c183185368882025d4bbd5b7f122d996041a5cba1f9cce6e6/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/6db9ba5a73f2d7e8c262329669e05a2ec3e37ac7f8bf31627986ecc6547db2f9/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/5d9972b897b8c8c2d6b8821c160986e31f51c4c02ebbb09c8f4b0802169264ad/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/c57f8edaa75b4bfa04412e03511aaddfd18a92aa73eea518564dc7df92d7c7cb/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/777b5e4001f295c54ce1b265ffa1889d1f6ac6d2b4ddfb5beeece6dd7f3d8a2e/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/b1e5f7a979ca4ec25c465c1fa53bc703a2edb593bf6c367ce09e82a01824b185/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/8c687211005b9df757a107e8f8a6c218a56061019e9bda756294422ce0bec542/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/aa6a1ae4e101ec0a761946c082e71e05a35ed6a00a4922872445e89fe231ecb4/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/06cd44d07304279d5310d490e41669233d7023d513b27a5e240e86f66ca2dcd5/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/d41f118ed8e2119f67358c10b60c4577cd19507494eb8a583be43a4195913ba4/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/9c22c0ce031b8c07be4f4116da67cedde2688da560f9fc4b92389c154dd0a1f2/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/4f58885ecc0ec422a5ac940aa0d56e4cc3254a7048671c2973f105b12a0a70ed/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/bf23c9a2e5f7570013cc1f5506f6b4092f69d17c8a8c3eb755e12c5c5c79e3ca/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/5419f36ff8e024010d355d45a55d584818689f47cfcf6bd1619cfba3a5206b1e/merged
/dev/loop14          squashfs      268928    268928         0 100% /mnt/host/snap/firefox/3687
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/ba7622703adea469fe9f68ba4f44b356f65fab6731c58b3564940fdfb0b861bd/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/cbc6f219c616b226dd5ff76585ce590a69ae675e02b7429d302fd651a2f2020f/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/47c80f7110798da34dc7ca84c4c8dc17bc82960302a0cb714e01eacb3941217f/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/fe39ced86fcb6ee402706f64e84c61370ff7106f6f8f77afa87dbbf1b20db0ff/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/f904eca96914ff352b7c5fadfc914a48aa098c02001dbeb6b8e48e92d60585b7/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/3a4ba91425d00073d83e6d14b7dd0ea41d4b6c8b8772714b8cdb8a44573fd5cf/merged
overlay              overlay    486202568 195889088 265542256  42% /mnt/host/var/lib/docker/overlay2/3a4ba91425d00073d83e6d14b7dd0ea41d4b6c8b8772714b8cdb8a44573fd5cf/merged
tmpfs                tmpfs          65536         0 df: /media/ben/Plex\040Movies: No such file or directory
df: /media/ben/Plex\040TV\040Shows: No such file or directory
df: /media/ben/External\040A: No such file or directory
    65536   0% /mnt/host/var/lib/docker/overlay2/3a4ba91425d00073d83e6d14b7dd0ea41d4b6c8b8772714b8cdb8a44573fd5cf/merged/dev
shm                  tmpfs          65536         0     65536   0% /mnt/host/var/lib/docker/overlay2/3a4ba91425d00073d83e6d14b7dd0ea41d4b6c8b8772714b8cdb8a44573fd5cf/merged/dev/shm
/dev/sdc5            ext4       486202568 195889088 265542256  42% /etc/resolv.conf
/dev/sdc5            ext4       486202568 195889088 265542256  42% /etc/hostname
/dev/sdc5            ext4       486202568 195889088 265542256  42% /etc/hosts
/dev/sda2            fuseblk    976744444  15631996 961112448   2% /media/ben/HDD
```

**Comment by blackadar** [comment]
Just an update, this is still a problem post- OS upgrade. Let me know if any info would be helpful :)

![image](https://github.com/MauriceNino/dashdot/assets/20449792/589e0e2a-e622-4974-a9ba-4e386635e481)

**Comment by blackadar** [comment]
Interestingly enough... switching to the nvidia tag fixed it for me:

![image](https://github.com/MauriceNino/dashdot/assets/20449792/37ca10c3-0c3b-44e9-831d-7ca6e8647fcc)

**Comment by GAS85** [comment]
I do removed real drives (`DASHDOT_FS_DEVICE_FILTER`) and replaced them with virtual one (`DASHDOT_FS_VIRTUAL_MOUNTS`):

```yaml
      - DASHDOT_FS_DEVICE_FILTER=sda,sdb,sdc,sdd
      - DASHDOT_FS_VIRTUAL_MOUNTS=/dev/mapper/ubuntu--vg-ubuntu--lv,/dev/mapper/raid--vg-data--lv,/dev/mapper/vg--smallraid-lv--smallraid
```

![Image](https://github.com/user-attachments/assets/e4315126-f3ea-4468-a79e-5d9408288d39)
